service: serverless

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  region: us-east-1
  stage: dev
  profile: serverless-servicename-agent

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/api.handler
    events:
      - http:
          path: /api
          method: GET
          cors: true
  todos:
    handler: src/api/todos.handler
    
  todo:
    handler: src/api/todo.handler
